### ISSUE TITLE
阿里云的“滑动验证页面”大家是怎么解决的？

### ISSUE THREAD

**Issue by guolei1998** [Kairu-Madigan/txffpAssistant#1]
运行一段时间，就会有滑动验证页面出现。

**Comment by huimingz** [comment]
@guolei1998 能否提供一个截图

**Comment by guolei1998** [comment]
就是应当获取正常页面源码的时候，出现了阿里云滑动验证页面的源码。我通过设置BaseHandler里的sleep_time解决了。得设置为1秒以上。

**Comment by huimingz** [comment]
@guolei1998 发布了新版本1.0.4，可以在命令行参数中指定请求睡眠间隔。有没有兴趣参与自动开票的测试，我没有环境进行开票测试，所以一直没有写这个功能。有兴趣参与测试的话，请加群863896565
